- project:
    queue: murano
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - murano-rally-task
        - murano-tempest-api
        - murano-tempest-cfapi
        - murano-grenade
        - murano-tempest-api-ipv6-only
    gate:
      jobs:
        - murano-tempest-api
        - murano-tempest-api-ipv6-only

- job:
    name: murano-rally-task
    voting: false
    parent: rally-task-murano
    irrelevant-files: &murano-irrelevant-files
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
      - ^contrib/.*$
      - ^tools/.*$
    timeout: 7800
    vars:
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
      rally_task: rally-jobs/task-murano.yaml
    required-projects:
      - openstack/rally-openstack

- job:
    name: murano-tempest-base
    parent: devstack-tempest
    irrelevant-files: *murano-irrelevant-files
    timeout: 7800
    required-projects: &base_required_projects
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/tempest
      - openstack/murano-tempest-plugin
    vars: &base_vars
      devstack_plugins:
        murano: https://opendev.org/openstack/murano
        heat: https://opendev.org/openstack/heat
      devstack_services:
        tempest: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      devstack_localrc:
        TEMPEST_PLUGINS: "/opt/stack/murano-tempest-plugin"
        KEYSTONE_ADMIN_ENDPOINT: true
      tempest_test_regex: application_catalog
      tox_envlist: all

- job:
    name: murano-tempest-api
    parent: murano-tempest-base

- job:
    name: murano-tempest-api-ipv6-only
    parent: devstack-tempest-ipv6
    description: |
      Murano devstack tempest tests job for IPv6-only deployment
    timeout: 7800
    irrelevant-files: *murano-irrelevant-files
    required-projects: *base_required_projects
    vars: *base_vars

- job:
    name: murano-tempest-cfapi
    parent: murano-tempest-base
    voting: false
    vars:
      devstack_services:
        murano-cfapi: true
      tempest_test_regex: service_broker

- job:
    name: murano-grenade
    parent: grenade
    voting: false
    irrelevant-files: *murano-irrelevant-files
    required-projects:
      - opendev.org/openstack/grenade
      - opendev.org/openstack/heat
      - opendev.org/openstack/murano
      - opendev.org/openstack/murano-dashboard
      - opendev.org/openstack/python-heatclient
      - opendev.org/openstack/python-muranoclient
      - opendev.org/openstack/murano-tempest-plugin
      - opendev.org/openstack/heat-tempest-plugin
    vars:
      grenade_localrc:
        RUN_HEAT_INTEGRATION_TESTS: False
      devstack_plugins:
        murano: https://opendev.org/openstack/murano
        heat: https://opendev.org/openstack/heat
      devstack_services:
        tempest: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        h-api: true
        h-api-cfn: true
        h-eng: true
        heat: true
      tempest_plugins:
        - murano-tempest-plugin
      tempest_test_regex: ^murano_tempest_tests\.tests\.scenario\.application_catalog\.test_deployment
      tox_envlist: all
