- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - periodic-stable-jobs
      - release-notes-jobs
    check:
      jobs:
        - murano-rally
        - murano-tempest-api
        - murano-tempest-cfapi
        - openstack-tox-cover:
            voting: false
    gate:
      queue: murano
      jobs:
        - murano-tempest-api
    experimental:
      jobs:
        - murano-functional

    post:
      jobs:
        - openstack-tox-cover

- job:
    name: murano-rally
    parent: legacy-dsvm-base
    run: playbooks/legacy/rally-dsvm-murano-task/run.yaml
    post-run: playbooks/legacy/rally-dsvm-murano-task/post.yaml
    voting: false
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/rally

- job:
    name: murano-tempest-api
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-dsvm-murano-api/run.yaml
    post-run: playbooks/legacy/tempest-dsvm-murano-api/post.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/tempest
      - openstack/murano-tempest-plugin

- job:
    name: murano-tempest-cfapi
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-dsvm-murano-cfapi/run.yaml
    post-run: playbooks/legacy/tempest-dsvm-murano-cfapi/post.yaml
    voting: false
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/tempest
      - openstack/murano-tempest-plugin

- job:
    name: murano-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/murano-dsvm-functional/run.yaml
    post-run: playbooks/legacy/murano-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
