- project:
    queue: murano
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - murano-rally-task
        - murano-tempest-api
        - murano-tempest-cfapi
        - murano-grenade
    gate:
      jobs:
        - murano-tempest-api

- job:
    name: murano-rally-task
    parent: rally-task-murano
    timeout: 7800
    voting: false
    vars:
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
      rally_task: rally-jobs/task-murano.yaml
    required-projects:
      - openstack/rally-openstack

- job:
    name: murano-tempest-base
    parent: devstack-tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
    timeout: 7800
    required-projects:
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/tempest
      - openstack/murano-tempest-plugin
    vars:
      devstack_plugins:
        murano: https://opendev.org/openstack/murano
        heat: https://opendev.org/openstack/heat
      devstack_services:
        tempest: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tls-proxy: false
      devstack_localrc:
        TEMPEST_PLUGINS: "/opt/stack/murano-tempest-plugin"
      tempest_test_regex: application_catalog
      tox_envlist: all

- job:
    name: murano-tempest-api
    parent: murano-tempest-base

- job:
    name: murano-tempest-cfapi
    parent: murano-tempest-base
    voting: false
    vars:
      devstack_services:
        murano-cfapi: true
      tempest_test_regex: service_broker

- job:
    name: murano-grenade
    parent: legacy-dsvm-base
    timeout: 10800
    voting: false
    run: playbooks/legacy/grenade-devstack-murano/run.yaml
    post-run: playbooks/legacy/grenade-devstack-murano/post.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^murano/tests/.*$
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/heat-tempest-plugin
      - openstack/murano-tempest-plugin
