#!/bin/bash

set -eu

if [ -e /etc/lsb-release ]; then
    if [ -e /usr/lib/apt/methods/https ]; then
        apt-get update
        apt-get install apt-transport-https
    fi
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
    echo "deb https://get.docker.com/ubuntu docker main" > /etc/apt/sources.list.d/docker.list
    apt-get update
    apt-get -y install lxc-docker
else
    yum -y install docker
fi