#!/bin/sh
### BEGIN INIT INFO
# Provides:          murano-agent
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       murano-agent service
### END INIT INFO

# NOTE(kzaitsev): not using fullpath to allow different locations
# of muranoagent binary on different OS images. muranoagent just needs
# to be in PATH. Up to image to decide where exactly.
SCRIPT="muranoagent --config-dir /etc/murano"
RUNAS=root

PIDFILE=/var/run/murano.pid
LOGFILE=/var/log/murano.log

start() {
  if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")"; then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service' >&2
  PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH"
  LOCAL_CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$LOCAL_CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 "$(cat "$PIDFILE")"; then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service' >&2
  kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
