#!/bin/bash

DEVSTACK_DIR=/home/stack/devstack

MYSQL_DB_TMPFS=true
MYSQL_DB_TMPFS_SIZE=128M

NOVA_CACHE_TMPFS=true
NOVA_CACHE_TMPFS_SIZE=24G


#======================================
source $DEVSTACK_DIR/openrc admin admin
source ./functions.sh

