#!/bin/bash

DEVSTACK_DIR=/home/stack/devstack
DEVSTACK_INSTALL_DIR=/opt/stack

MYSQL_DB_TMPFS=true
MYSQL_DB_TMPFS_SIZE=128M

NOVA_CACHE_TMPFS=true
NOVA_CACHE_TMPFS_SIZE=24G

GLANCE_IMAGE_LIST=""
COMPUTE_NODE_LIST="172.18.124.102"

#======================================
if [[ -d "$DEVSTACK_DIR" ]] ; then
    source $DEVSTACK_DIR/openrc admin admin
fi
source $SCRIPTS_DIR/functions.sh

